schema_version = "1.0.0"
id = "Mask_To_Vertex_Color_Pro"
name = "MaskToVertexColorPro"
version = "2.0.4"
tagline = "Mask To VertexColor Pro Tools"
maintainer = "хвиц│к"
type = "add-on"
blender_version_min = "4.2.0"
tags = ["Paint", "Material"]
license = ["SPDX:GPL-3.0-or-later"]
website = "https://www.kiiiii.com"

[permissions]
files = "Import images are required as masks"
